export const SENSOR_STATE_CLASSES = ["measurement", "total", "total_increasing"] as const;
export const ENTITY_CATEGORIES = ["config", "diagnostic"] as const;

export { MDI_ICON_NAMES } from "./mdi-icons";

// Sensor device classes (subset; expand as needed).
// Source: https://www.home-assistant.io/integrations/sensor/#device-class
export const SENSOR_DEVICE_CLASSES = [
  "apparent_power",
  "aqi",
  "atmospheric_pressure",
  "battery",
  "carbon_dioxide",
  "carbon_monoxide",
  "current",
  "data_rate",
  "data_size",
  "date",
  "distance",
  "duration",
  "energy",
  "energy_storage",
  "enum",
  "frequency",
  "gas",
  "humidity",
  "illuminance",
  "irradiance",
  "moisture",
  "monetary",
  "nitrogen_dioxide",
  "nitrogen_monoxide",
  "nitrous_oxide",
  "ozone",
  "ph",
  "pm1",
  "pm10",
  "pm25",
  "power",
  "power_factor",
  "precipitation",
  "precipitation_intensity",
  "pressure",
  "reactive_power",
  "signal_strength",
  "sound_pressure",
  "speed",
  "sulphur_dioxide",
  "temperature",
  "timestamp",
  "volatile_organic_compounds",
  "volatile_organic_compounds_parts",
  "voltage",
  "volume",
  "volume_storage",
  "volume_flow_rate",
  "water",
  "weight",
  "wind_speed",
] as const;
